---
title: "Ficha2"
author: "Diogo Silva"
date: "2025-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Os dados da tabela representam o comprimento alar em função da idade de andorinhas.
Verifique se existe uma relação linear entre as duas variáveis.
Idade (dias) 3 4 5 6 8 9 10 11 12 14 15 16 17
Comprimento Alar (cm) 1.4 1.5 2.2 2.4 3.1 3.2 3.2 3.9 4.1 4.7 4.5 5.2 5.0

```{r}
#dados = read.csv("dados_Ficha2/comp_alar.txt", header = TRUE, sep=" ",dec=".")
#dados


idade = c(3,4,5,6,8,9,10,11,12,14,15,16,17)

comprAlar = c(1.4,1.5,2.2,2.4,3.1,3.2,3.2,3.9,4.1,4.7,4.5,5.2,5.0)

x= idade
y = comprAlar

```


## Gráfico de dispersão 
```{r}
plot(x,y,main="Gráfico Dispersão sem dataframe",col="red",xlab = "Idades", ylab="Comprimento Alar em cm")
```
```{r}
#yhat é um objeto que é um dataframe com vários objetos
yhat = lm(y~x)
plot(y,x,main="Gráfico Dispersão utilizando dataframe",col="red",xlab = "Idades", ylab="Comprimento Alar em cm")
abline(lm(y~x), lty = 2)
summary(yhat)
```
- yhat é um objeto que é um dataframe com vários objetos

```{r}
predict(yhat,data.frame(x=sort(x)),level = .95, interval="confidence")
plot(x,y)
abline(yhat)
```

```{r}
ci.lwr = predict(yhat,data.frame(x=sort(x)),level=.95,interval="confidence")[,2]

points(sort(x),ci.lwr,type="1",lty=2)
curve(predict(yhat,data.frame(x=x),interval = "confidence"))
```

